In [1]:
import pandas as pd
import numpy as np
import joblib
import os
import warnings
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('Crop_recommendation.csv')


In [10]:
feature_cols = df.columns.drop('label')
df[feature_cols] = df[feature_cols].apply(pd.to_numeric, errors='coerce')


In [11]:
df_clean = df.dropna()


In [12]:
Q1 = df_clean[feature_cols].quantile(0.25)
Q3 = df_clean[feature_cols].quantile(0.75)
IQR = Q3 - Q1

In [6]:
df_clean = df_clean.dropna()


In [13]:
condition = ~((df_clean[feature_cols] < (Q1 - 1.5 * IQR)) | (df_clean[feature_cols] > (Q3 + 1.5 * IQR))).any(axis=1)
df_out = df_clean[condition]

In [14]:
X = df_out[feature_cols]
y = df_out['label']

In [9]:
df_out = df_clean[condition]


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [16]:
pipeline = make_pipeline(StandardScaler(), GaussianNB())


In [17]:
model = pipeline.fit(X_train, y_train)


In [18]:
y_pred = model.predict(X_test)


In [19]:
accuracy = accuracy_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


In [20]:
print("Training completed!")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(conf_mat)
print("Classification Report:")
print(class_report)

Training completed!
Accuracy: 98.59%
Confusion Matrix:
[[21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0 18  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0 13  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0]


In [ ]:
joblib.dump(model, 'model1.joblib')

print("Model saved as 'model.joblib'.")

Model saved as 'model.joblib'.


In [25]:
import streamlit as st
print(st.__version__)

1.48.0


In [27]:
import plotly
print(plotly.__version__)

6.3.1


In [28]:
import seaborn
print(seaborn.__version__)

0.13.2


In [29]:
print(pd.__version__)

2.3.1


In [30]:
import matplotlib
print(matplotlib.__version__)

3.10.3


In [32]:
import sklearn
print(sklearn.__version__)

1.7.1


In [33]:
import joblib
print(joblib.__version__)

1.5.1
